### ISSUE TITLE
Email in stock notification error

### ISSUE THREAD

**Issue by trillox9** [zanedma/Newegg-scraper#1]
<HttpError 400 when requesting https://gmail.googleapis.com/gmail/v1/users/me/messages/send?alt=json returned "Recipient address required". Details: "[{'message': 'Recipient address required', 'domain': 'global', 'reason': 'invalidArgument'}]">
I get this error if item is in stock and i try to receive email, can you help me? thank you

**Comment by zanedma** [comment]
I just pushed an updated version that fixes that issue
